parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

env:
  browser: true
  es6: true
  node: true
  jest: true

plugins:
  - import
  - sonarjs

extends:
  - eslint:recommended
  - plugin:sonarjs/recommended
  - plugin:prettier/recommended

rules:
  # 0 = off, 1 = warn, 2 = error
  "space-before-function-paren": 0
  "semi": [2, "always"]
  "no-useless-constructor": 0
  "no-undef": 2
  "no-console": [2, { allow: ["error", "warn", "info", "assert"] }]
  "comma-dangle": ["error", "only-multiline"]
  "no-unused-vars": 0
  "no-var": 2
  "one-var-declaration-per-line": 2
  "prefer-const": 2
  "no-const-assign": 2
  "no-duplicate-imports": 2
  "no-use-before-define": [2, { "functions": false, "classes": false }]
  "eqeqeq": [2, "always", { "null": "ignore" }]
  "no-case-declarations": 0
  "no-restricted-syntax":
    [
      2,
      {
        "selector": "BinaryExpression[operator=/(==|===|!=|!==)/][left.raw=true], BinaryExpression[operator=/(==|===|!=|!==)/][right.raw=true]",
        "message": Don't compare for equality against boolean literals,
      },
    ]

  # https://github.com/benmosher/eslint-plugin-import/pull/334
  "import/no-duplicates": 2
  "import/first": 2
  "import/newline-after-import": 2
  "import/order":
    [
      2,
      {
        "newlines-between": "always",
        "alphabetize": { "order": "asc" },
        "groups":
          ["builtin", "external", "internal", "parent", "sibling", "index"],
      },
    ]

  "sonarjs/cognitive-complexity": 0
  "sonarjs/no-duplicate-string": 0
  "sonarjs/no-big-function": 0
  "sonarjs/no-identical-functions": 0
  "sonarjs/no-small-switch": 0
  "prettier/prettier": ["error", { "semi": true }]
